# Generated by Django 4.2.13 on 2024-05-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SUCCESS', 'Success')], max_length=10)),
                ('log_string', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('metadata_source', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='QL_Interfac_timesta_dd7d37_idx'), models.Index(fields=['level'], name='QL_Interfac_level_154db2_idx'), models.Index(fields=['metadata_source'], name='QL_Interfac_metadat_97e4ab_idx')],
            },
        ),
    ]
